name: Optimize map and deploy

on:
  - push

jobs:

  deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Optimize map
        uses: thecodingmachine/map-optimizer-action@master
